# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MTSM
                                 A QGIS plugin
 MT survey manager
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-04
        copyright            : (C) 2025 by Adam Grand
        email                : adam.grand@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MTSM class from file MTSM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MTSM import MTSM
    return MTSM(iface)
